### ISSUE TITLE
Inquiry about Method Caller Extraction in Java Library project Using Tai-e

### ISSUE THREAD

**Issue by vbifg** [pascal-lab/Tai-e#113]
### Overall Description

Hello,
I am currently analyzing a Java library application project named _P_library_ using Tai-e. My goal is to **extract the function signatures of all callers of the _getData_ method defined in the _example.java_ file across the _P_library_ project.** Since the library lacks a main function and the _getData_ method contains bugs, I modified the _onStart()_ function in _EntryPointHandler.java_ within Tai-e. I set it to trigger the bug-invoking test method in the _P_library_ project's JUnit tests, knowing this would reach the _getData_ method, in an attempt to capture all callers of this method throughout the project. However, I've encountered some issues:
1. The extracted callers are incomplete. During debugging, I realized that the construction of the call graph also starts from the entry point, which may be due to incomplete test coverage.
2. The extraction is inaccurate. Although the method name getData is the same, the extracted callers are from another file's _getData_, not the one from _example.java_.
 
Could you please advise if it is possible to accurately extract the function signatures of all callers for the _getData_ method defined in _example.java_ within the _P_library_ project using Tai-e? 
I look forward to your response and am willing to provide any additional information needed. Thank you very much.

### Expected Behavior

Extract the function signatures of all callers of the getData method defined in the example.java file across the P_library project.

### Current Behavior

1. The extracted callers are incomplete. During debugging, I realized that the construction of the call graph also starts from the entry point, which may be due to incomplete test coverage.
2. The extraction is inaccurate. Although the method name getData is the same, the extracted callers are from another file's getData, not the one from example.java.

### Tai-e Arguments

<details>
  <summary>Click here to see Tai-e Options</summary>
  

  ```yaml
  {{optionsFile: null
printHelp: false
classPath:
- ../docker_code/P_Library/lib/junit.jar
- ../docker_code/P_Library/target/P_Library_tests.jar
- ../docker_code/P_Library/target/P_Library_source.jar
appClassPath: []
mainClass: null
inputClasses:
- org.example
javaVersion: 6
prependJVM: false
allowPhantom: false
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: true
scope: APP
nativeModel: true
planFile: null
analyses:
  pta: cs:2-obj;only-app:true;implicit-entries:true;handle-invokedynamic:true
  cg: algorithm:pta;dump:true;dump-methods:true;dump-call-edges:true
  process-result: "analyses:[cg];action:dump;action-file:caller_main.txt"
onlyGenPlan: false
keepResult:
- $KEEP-ALL
}}
  ```
</details>
<details>
  <summary>Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  {{- id: pta
  options:
    cs: 2-obj
    only-app: true
    implicit-entries: true
    distinguish-string-constants: reflection
    merge-string-objects: true
    merge-string-builders: true
    merge-exception-objects: true
    handle-invokedynamic: true
    propagate-types:
    - reference
    advanced: null
    dump: false
    dump-ci: false
    dump-yaml: false
    expected-file: null
    reflection-inference: string-constant
    reflection-log: null
    taint-config: null
    taint-interactive-mode: false
    plugins: []
    time-limit: -1
- id: cg
  options:
    algorithm: pta
    dump: true
    dump-methods: true
    dump-call-edges: true
- id: process-result
  options:
    analyses:
    - cg
    only-app: true
    action: dump
    action-file: caller_main.txt
    log-mismatches: false
}}
  ```
</details>

### Tai-e Log

<details>
  <summary>Click here to see Tai-e Log</summary>
  

  ```
  {{Writing log to /Users/kkk/Tai-e/output/tai-e.log
java.version: 17.0.11
java.version.date: 2024-04-16
java.runtime.version: 17.0.11+9-LTS
java.vendor: Amazon.com Inc.
java.vendor.version: Corretto-17.0.11.9.1
os.name: Mac OS X
os.version: 14.5
os.arch: x86_64
Tai-e Version: 0.5.1-SNAPSHOT
Tai-e Commit: f3e1891c84a3b493636683583267aff5ef698aa2
Writing analysis plan to /Users/kkk/Tai-e/output/tai-e-plan.yml
WorldBuilder starts ...
The world cache mode is enabled.
Loading the world cache from /Users/kkk/Tai-e/cache/world-cache-283076132.bin
[Load the world cache] elapsed time: 1426.66s
5879 classes with 57910 methods in the world
WorldBuilder finishes, elapsed time: 1426.86s
pta starts ...
}}
  ```
</details>
