### ISSUE TITLE
Get some trouble on using taint analysis

### ISSUE THREAD

**Issue by f4nx1ng** [pascal-lab/Tai-e#124]
### 📝 Overall Description

When I used the framework for taint analysis, I found that the framework did not perform taint propagation well. Specifically, when I tried to detect the URLDNS deserialization gadget chain, Tai-e did not achieve the expected effect. So I want to know if this is a bug

### 🎯 Expected Behavior

The result should be a taint flow path from <java.util.HashMap: void readObject(java.io.ObjectInputStream)> to <java.net.URLStreamHandler: int hashCode(java.net.URL)>

### 🐛 Current Behavior

Tai-e report nothing to me

### 🔄 Reproducible Example

[issue-package.zip](https://github.com/user-attachments/files/17457868/issue-package.zip)

### ⚙️ Tai-e Arguments

<details>
  <summary>🔍 Click here to see Tai-e Options</summary>
  

  ```yaml
  optionsFile: null
printHelp: false
classPath: null
appClassPath: java-benchmarks/urldns
mainClass: URLDNS
inputClasses: []
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  #  ir-dumper: ;
  pta: cs:ci;implicit-entries:false;distinguish-string-constants:null;reflection-inference:solar;merge-string-objects:false;merge-string-builders:false;merge-exception-objects:false;taint-config:config/unserialize/taint-config.yml;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
  ```
</details>
<details>
  <summary>🔍 Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  - id: pta
  options:
    cs: ci
    only-app: false
    implicit-entries: false
    distinguish-string-constants: null
    merge-string-objects: false
    merge-string-builders: false
    merge-exception-objects: false
    handle-invokedynamic: false
    propagate-types:
    - reference
    advanced: null
    dump: false
    dump-ci: false
    dump-yaml: false
    expected-file: null
    reflection-inference: solar
    reflection-log: null
    taint-config: config/unserialize/taint-config.yml
    plugins: []
    time-limit: -1
  ```
</details>

### 📜 Tai-e Log

<details>
  <summary>🔍 Click here to see Tai-e Log</summary>
  

  ```
  Writing log to D:\IDEA_Projects\Tai-e\output\tai-e.log
Writing analysis plan to D:\IDEA_Projects\Tai-e\output\tai-e-plan.yml
WorldBuilder starts ...
6702 classes with 64239 methods in the world
WorldBuilder finishes, elapsed time: 2.06s
pta starts ...
Loading taint config from D:\IDEA_Projects\Tai-e\config\unserialize\taint-config.yml
TaintConfig:
sources:
  ParamSource{<java.util.HashMap: void readObject(java.io.ObjectInputStream)>/0(java.io.ObjectInputStream)}
  CallSource{<java.net.URLStreamHandler: int hashCode(java.net.URL)>/0(java.net.URL)}

sinks:
  <java.net.InetAddress: java.net.InetAddress getByName(java.lang.String)>/0
  <java.net.URLStreamHandler: int hashCode(java.net.URL)>/base

transfers:
  <java.io.ByteArrayInputStream: void <init>(byte[])>: 0 -> base(java.io.ByteArrayInputStream)
  <java.io.ObjectInputStream: void <init>(java.io.InputStream)>: 0 -> base(java.io.ObjectInputStream)
  <java.io.ObjectInputStream: java.lang.Object readObject()>: base -> result(java.lang.Object)
  <java.net.URLStreamHandler: int hashCode(java.net.URL)>: 0 -> base(java.net.URLStreamHandler)

[Pointer analysis] elapsed time: 12.68s
Detected 0 taint flow(s):
TFGDumper starts ...
Source nodes:
VarNode{<java.util.HashMap: void readObject(java.io.ObjectInputStream)>/r0}
Sink nodes:
Dumping D:\IDEA_Projects\Tai-e\output\taint-flow-graph.dot
TFGDumper finishes, elapsed time: 0.27s
-------------- Pointer analysis statistics: --------------
#var pointers:                6,2704 (insens) / 6,2704 (sens)
#objects:                     9035 (insens) / 9035 (sens)
#var points-to:               833,8344 (insens) / 833,8344 (sens)
#static field points-to:      1935 (sens)
#instance field points-to:    282,3617 (sens)
#array points-to:             7,1176 (sens)
#reachable methods:           9201 (insens) / 9201 (sens)
#call graph edges:            5,2780 (insens) / 5,2780 (sens)
----------------------------------------
pta finishes, elapsed time: 14.74s
  ```
</details>

### ℹ️ Additional Information

In addition to the above information, I also added a Tai-e analysis plugin to identify the entry, As shown below
```java
public class UnserializeEntryPointHandler implements Plugin {
    private Solver solver;
    private String findclass = "java.util.HashMap";

    @Override
    public void setSolver(Solver solver) {
        this.solver = solver;
    }

    @Override
    public void onStart() {
        //add HashMap readObject to EntryPoint
        List<JClass> list = solver.getHierarchy().allClasses().toList();
        List<Type> paramType = new ArrayList<>();
        for(JClass jClass : list){
            if(jClass.getName().equals(findclass)){
                System.out.println("find class");
//                paramType.add(NullType.NULL);
                //Subsignature subsignature = Subsignature.get("readObject", paramType, new ClassType(jClass.getClassLoader(), "java.lang.Object"));
                JMethod jMethod = jClass.getDeclaredMethod("readObject");
                if(jMethod != null){
                    System.out.println("entry add");
                    solver.addEntryPoint(new EntryPoint(jMethod, new DeclaredParamProvider(jMethod, solver.getHeapModel())));
                }
            }
        }
    }
}
```
