### ISSUE TITLE
interclass interfaces is empty

### ISSUE THREAD

**Issue by f4nx1ng** [pascal-lab/Tai-e#128]
### 📝 Overall Description

When I was analyzing a file named aspectjweaver-1.9.4.jar, there was a class named org.aaspectj.weaver.tools.comach When I debugged SimpleCache $StoreableCachingMap to see the implementation information of the interface of this class, I found that the content was empty. As shown in the picture below, may I ask if this is a mechanism or an error
![image](https://github.com/user-attachments/assets/fea0154e-951f-47a5-899a-874116c34292)

### 🎯 Expected Behavior

As shown in the previous image, this class inherits HashMap, so it should also inherit the interface implemented by HashMap. However, I did not find a corresponding item from the variable pool.

### 🐛 Current Behavior

![image](https://github.com/user-attachments/assets/fea0154e-951f-47a5-899a-874116c34292)

### 🔄 Reproducible Example

You can see more details in my repo
https://github.com/f4nx1ng/Tai-e/tree/master/mybeanchmark/AspectJWeaver
https://github.com/f4nx1ng/Tai-e/blob/master/src/main/java/pascal/taie/analysis/pta/plugin/TestHandler.java

### ⚙️ Tai-e Arguments

<details>
  <summary>🔍 Click here to see Tai-e Options</summary>
  

  ```yaml
  optionsFile: null
printHelp: false
classPath: []
appClassPath:
  - mybeanchmark/AspectJWeaver
  - mybeanchmark/AspectJWeaver/aspectjweaver-1.9.4.jar
  - mybeanchmark/AspectJWeaver/commons-collections-3.2.2.jar
mainClass: AspectJWeaver
inputClasses: []
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: true
worldCacheMode: false
scope: ALL
nativeModel: true
planFile: null
analyses:
  pta: cs:ci;implicit-entries:false;distinguish-string-constants:null;reflection-inference:solar;taint-config:mybeanchmark/AspectJWeaver/taint-config.yml; #dump-ci:true;
onlyGenPlan: false
keepResult:
  - $KEEP-ALL
  ```
</details>
<details>
  <summary>🔍 Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
  - id: pta
  options:
    cs: ci
    only-app: false
    implicit-entries: false
    distinguish-string-constants: null
    merge-string-objects: true
    merge-string-builders: true
    merge-exception-objects: true
    handle-invokedynamic: false
    propagate-types:
    - reference
    advanced: null
    dump: false
    dump-ci: false
    dump-yaml: false
    expected-file: null
    reflection-inference: solar
    reflection-log: null
    taint-config: mybeanchmark/AspectJWeaver/taint-config.yml
    taint-config-providers: []
    taint-interactive-mode: false
    plugins: []
    time-limit: -1
  ```
</details>

### 📜 Tai-e Log

<details>
  <summary>🔍 Click here to see Tai-e Log</summary>
  

  ```
  {{The content of 'output/tai-e.log' file}}
  ```
</details>
