### ISSUE TITLE
A False Positive Taint Flow between Entry Points

### ISSUE THREAD

**Issue by elteammate** [pascal-lab/Tai-e#167]
### 📝 Overall Description

When using multiple entry points, taint analysis gets confused and reports taint flows between entry points.

For example, consider a class:
```java
public class Main {
    public void sink(String s) {}

    public void entry1(String x) {
        sink(x + "a");
    }

    public void entry2(String x) {
        sink(x + "b");
    }
}
```
Here `entry1` and `entry2` are entry points, as defined by a plugin, and both have parameters marked as sources. `sink` method is the only sink.

Tai-e reports 4 taint flows here, seemingly regardless of sensitivity settings.
```
TaintFlow{<Main: void entry1(java.lang.String)>/0 -> <Main: void entry1(java.lang.String)>[6@L5] invokevirtual %this.sink($r5)/0}
TaintFlow{<Main: void entry1(java.lang.String)>/0 -> <Main: void entry2(java.lang.String)>[6@L9] invokevirtual %this.sink($r5)/0}
TaintFlow{<Main: void entry2(java.lang.String)>/0 -> <Main: void entry1(java.lang.String)>[6@L5] invokevirtual %this.sink($r5)/0}
TaintFlow{<Main: void entry2(java.lang.String)>/0 -> <Main: void entry2(java.lang.String)>[6@L9] invokevirtual %this.sink($r5)/0}
```

Note that this behavior is not reproducible if the use of `StringBuilder` (in + operator for strings) is omitted.

### 🎯 Expected Behavior

Taint flow should report only two taint flows, each constraint to the entry point it appeared from.

### 🐛 Current Behavior

Taint flow reports four taint flows, two of which are clearly wrong. Context sensitivity or disabling merging of strings and string builders does not help.

### 🔄 Reproducible Example

Please see this for the full reproducible example:
https://github.com/elteammate/tai-e-sqli/tree/tai-e-sus-tfg

TLDR:
1. Try to analyze a class as above:
```java
public class Main {
    public void sink(String s) {}

    public void entry1(String x) {
        sink(x + "a");
    }

    public void entry2(String x) {
        sink(x + "b");
    }
}
```
2. Implement a plugin which adds extra entry points ([see this file](http://github.com/elteammate/tai-e-sqli/blob/tai-e-sus-tfg/src/main/java/org/example/TestExtraEntryPoints.java)):
```java
public class TestExtraEntryPoints implements Plugin {
    private Solver theSolver;

    @Override
    public void setSolver(Solver solver) {
        if (solver != null) {
            theSolver = solver;
        }
        Plugin.super.setSolver(solver);
    }

    @Override
    public void onStart() {
        for (JClass cls : World.get().getClassHierarchy().allClasses().toList()) {
            if (!cls.getName().equals("Main")) continue;
            for (JMethod method : cls.getDeclaredMethods()) {
                if (method.getName().startsWith("entry")) {
                    theSolver.addEntryPoint(new EntryPoint(
                            method,
                            new DeclaredParamProvider(method, theSolver.getHeapModel(), 2)
                    ));
                }
            }
        }
    }
}
```
3. Add a sink and sources. I do that programmatically ([see this file for details](http://github.com/elteammate/tai-e-sqli/blob/tai-e-sus-tfg/src/main/java/org/example/TestExtraEntryPoints.java)):
```
sources:
  - { kind: "param", method: "<Main: void entry1(java.lang.String)>", index: "0", type: "java.lang.String" }
  - { kind: "param", method: "<Main: void entry2(java.lang.String)>", index: "0", type: "java.lang.String" }

sinks:
  - { method: "<Main: void sink(java.lang.String)>", index: "0" }
```
4. Compile example and run taint analysis (using provided string taint transfers)
```bash
mkdir -p /tmp/classes &&
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/javac Main.java -d /tmp/classes &&
./gradlew :fatJar &&
java \
  -jar build/tai-e-all-0.5.1.jar \
  -a "pta=cs:2-type;distinguish-string-constants:all;merge-string-objects:false;merge-string-builders:false;plugins:[org.example.TestExtraEntryPoints];taint-config:taint-config;taint-config-providers:[org.example.TestConfigProvider]" \
  -a "ir-dumper" \
  -java 8 \
  -ap \
  -cp /tmp/classes \
  --input-classes=Main
```

### ⚙️ Tai-e Arguments

<details>
  <summary>🔍 Click here to see Tai-e Options</summary>
  

  ```yaml
optionsFile: null
printHelp: false
classPath:
- ../../../../usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar
- java-sec-code/target/classes
appClassPath: []
mainClass: null
inputClasses:
- org.joychou.controller.SQLI
javaVersion: 8
prependJVM: false
allowPhantom: true
worldBuilderClass: pascal.taie.frontend.soot.SootWorldBuilder
outputDir: output
preBuildIR: false
worldCacheMode: false
scope: APP
nativeModel: true
planFile: null
analyses:
  pta: "cs:ci;dump-ci:true;plugins:[org.example.ExtraEntryPoints];taint-config:/home/elt/projects/confusion/taint-config;taint-config-providers:[org.example.MyTaintConfigProvider]"
  ir-dumper: ""
onlyGenPlan: false
keepResult:
- $KEEP-ALL
  ```
</details>
<details>
  <summary>🔍 Click here to see Tai-e Analysis Plan</summary>
  

  ```yaml
- id: pta
  options:
    cs: ci
    only-app: false
    implicit-entries: true
    distinguish-string-constants: reflection
    merge-string-objects: true
    merge-string-builders: true
    merge-exception-objects: true
    handle-invokedynamic: false
    propagate-types:
    - reference
    advanced: null
    dump: false
    dump-ci: true
    dump-yaml: false
    expected-file: null
    reflection-inference: string-constant
    reflection-log: null
    taint-config: /home/elt/projects/confusion/taint-config
    taint-config-providers:
    - org.example.MyTaintConfigProvider
    taint-interactive-mode: false
    plugins:
    - org.example.ExtraEntryPoints
    time-limit: -1
- id: ir-dumper
  options: {}
  ```
</details>

### 📜 Tai-e Log

<details>
  <summary>🔍 Click here to see Tai-e Log</summary>
  

  ```
Writing log to /home/elt/projects/confusion/output/tai-e.log
java.version: 17.0.15
java.version.date: 2025-04-15
java.runtime.version: 17.0.15+6-Ubuntu-0ubuntu124.04
java.vendor: Ubuntu
java.vendor.version: null
os.name: Linux
os.version: 6.8.0-60-generic
os.arch: amd64
Failed to read version from 'gradle.properties': java.io.FileNotFoundException: gradle.properties (No such file or directory)
Tai-e Version: Unknown
Failed to read Git commit hash: java.nio.file.NoSuchFileException: .git/HEAD
Tai-e Commit: Unknown
Writing analysis plan to /home/elt/projects/confusion/output/tai-e-plan.yml
WorldBuilder starts ...
  ```
</details>

### ℹ️ Additional Information

I apologize for working within Tai-e repository directly, since this must have affected the version in the log file. I use the latest 0.5.2 snapshot.
