### ISSUE TITLE
Ignoring array load of primitive type causes taint flow interruption

### ISSUE THREAD

**Issue by chennbnbnb** [pascal-lab/Tai-e#22]
I notice that: for point analysis, it will ignore array load or store stmt if array consists of primitive type elements.
follow is code in `DefaultSolver`
```java
public class DefaultSolver implements Solver {
    private static boolean isConcerned(Exp exp) { 
        Type type = exp.getType();
        return type instanceof ReferenceType && !(type instanceof NullType);
    }

    private void processArrayLoad(CSVar arrayVar, PointsToSet pts) {
        Context context = arrayVar.getContext();
        Var var = arrayVar.getVar();
        for (LoadArray load : var.getLoadArrays()) {  
            Var lvalue = load.getLValue();  
            if (isConcerned(lvalue)) {
                ...
            }
        }
    }
    ...
}
```

it work well for point analysis, because primitive isn't a pointer, can't pass object reference.
But In Taint analysis, I think ignoring primitive type array isn't good choice. 
follow is an example
```java
char[] buffer;
String str = sources();    // taint object, type=String
buffer = str.toCharArray();    // ignored, even if add taint transfer rules
sink(buffer)    
```
Essentially, Taint analysis focus on variable value, and value can be passed through primitive type variable too.  therefore Ignoring primitive type causes taint flow interruption.
Maybe we should take primitive type into account for taint analysis?

**Comment by zhangt2333** [comment]
`char[]` is not primitive type (but `char` is), so Tai-e donot ignore `char[]` in pointer analysis.

It seems that the issue is with the transfer rule (or its process). What are your taint rules?

**Comment by chennbnbnb** [comment]
IR for this method:
```java
    public org.apache.commons.text.TextStringBuilder append(java.lang.String str, int startIndex, int length) {
        ...
        [24@L642] $r4 = %this.<org.apache.commons.text.TextStringBuilder: char[] buffer>;
        [25@L642] invokevirtual str.<java.lang.String: void getChars(int,int,char[],int)>(startIndex, $i7, $r4, $i5);
       
        [26@L643] $i8 = %this.<org.apache.commons.text.TextStringBuilder: int size>;
        [27@L643] $i9 = $i8 + length;
        [28@L643] %this.<org.apache.commons.text.TextStringBuilder: int size> = $i9;
        [29@L645] return %this;
    }
```
notiablly: 
`[24@L642]`: tai adding a PFG edge: `this_obj.buffer->$r4`
`[25@L642] `: taint transfer add new taint object into `pts($r4)`, but this new taint object can't propagate to `this_obj.buffer` because there is no such edge in PFG

**Comment by silverbullettt** [comment]
@chennbnbnb We have extended the taint analysis in [this branch](https://github.com/pascal-lab/Tai-e/tree/taint-back-propagate) to handle your case, and you could try if it fixes your problem.

Currently we just handle specific case (loaded from instance field) as a too general handling of alias and mutable objects may cause precision and efficiency issues. If you encounter some cases that causes taint flow interruption, please let us know. Thanks.

**Comment by silverbullettt** [comment]
The change has been merged into [`master`](https://github.com/pascal-lab/Tai-e/commit/55433f76089786ef867546e7b915c0b8aa18a56f). Close as no response.

**Comment by struce2** [comment]
> @chennbnbnb We have extended the taint analysis in [this branch](https://github.com/pascal-lab/Tai-e/tree/taint-back-propagate) to handle your case, and you could try and see if it fixes your problem.
> 
> Currently we just handle specific case (loaded from instance field) as a too general handling of alias and mutable objects may cause precision and efficiency issues. If you encounter some other cases that causes taint flow interruption, please let us know. Thanks.

[Here is a real code](https://github.com/fa1c0n1/MyJSPWebshell/blob/master/web/webshell4.jsp) , `decoder.decode` will cause taint break, if replace `decoder.decode(clsbytecodeb64)` with `clsbytecodeb64.getBytes()` it will work.

This is TaintConfig
```yml
sources:
  - { method: "<javax.servlet.ServletRequest: java.lang.String getParameter(java.lang.String)>", type: "java.lang.String" }
  - { method: "<javax.servlet.ServletRequestWrapper: java.lang.String getParameter(java.lang.String)>", type: "java.lang.String"}

sinks:
  - { method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String)>", index: 0 }
  - { method: "<java.lang.ClassLoader: java.lang.Class defineClass(byte[],int,int)>", index: 0}

transfers:
  - { method: "<java.util.Base64$Decoder: byte[] decode(byte[])>", from: 0, to: result, type: "byte[]" }
  - { method: "<java.util.Base64$Decoder: int decode(byte[],byte[])>", from: 0, to: 1, type: "byte[]"}
  - { method: "<java.util.Base64$Decoder: byte[] decode(java.lang.String)>", from: 0, to: result, type: "byte[]" }
  - { method: "<java.lang.String: byte[] getBytes()>", from: base, to: result, type: "byte[]" }

```
