### ISSUE TITLE
The CLI output detected the taint flow, but no flow in the dot file.

### ISSUE THREAD

**Issue by Reclu3e** [pascal-lab/Tai-e#69]
## source code
```java
public class Main {
    public static void main(String[] args) {
        test1();
    }

    public static void test1(){
        String a = getSourceString();

        String [] b;
        b = a.split(":");

        TestSink.testStringSink(b[0]);
    }
    public static String getSourceString(){
        return "test1:test2";
    }
}
```
## IR
```
    public static void test1() {
        java.lang.String $r0, %stringconst0, $r2;
        java.lang.String[] $r1;
        int %intconst1;
        [0@L12] $r0 = invokestatic <org.example.Main: java.lang.String getSourceString()>();
        [1@L15] %stringconst0 = ":";
        [2@L15] $r1 = invokevirtual $r0.<java.lang.String: java.lang.String[] split(java.lang.String)>(%stringconst0);
        [3@L17] %intconst1 = 0;
        [4@L17] $r2 = $r1[%intconst1];
        [5@L17] invokestatic <org.example.TestSink: void testStringSink(java.lang.String)>($r2);
        [6@L18] return;
    }
```
## tai-e options
- options
```yaml
analyses:
  pta: cs:ci;implicit-entries:true;distinguish-string-constants:null;reflection-inference:solar;taint-config:java-benchmarks/common-text/taint-config.yml;
```
- taint-config
```yaml
sources:
  - { kind: call, method: "<org.example.Main: java.lang.String getSourceString()>", index: result }
sinks:
  - { method: "<org.example.TestSink: void testStringSink(java.lang.String)>", index: 0 }

transfers:
  - { method: "<java.lang.String: java.lang.String[] split(java.lang.String)>", from: base, to: "result[*]" }


```
## output 
- cli
```
TaintConfig:
sources:
  CallSource{<org.example.Main: java.lang.String getSourceString()>/result(java.lang.String)}
  CallSource{<org.example.Main: java.lang.String[] getSourceStringArray()>/result(java.lang.String[])}

sinks:
  <org.example.TestSink: void testStringSink(java.lang.String)>/0

[Pointer analysis] elapsed time: 5.47s
Detected 1 taint flow(s):
TaintFlow{<org.example.Main: void test1()>[0@L11] $r0 = invokestatic org.example.Main.getSourceString()/result -> <org.example.Main: void test1()>[5@L16] invokestatic org.example.TestSink.testStringSink($r2)/0}
TFGDumper starts ...
Source nodes:
VarNode{<org.example.Main: void test1()>/$r0}
Sink nodes:
VarNode{<org.example.Main: void test1()>/$r2}
```
- dot
![image](https://github.com/pascal-lab/Tai-e/assets/47467195/8a00437f-1519-499f-af83-42db7200bb08)

## question
- Is the output without edge in dot file as expected?   
  I think expected result should have at least 2 point flow edge: `$r0 -> $r1` and `$r1 -> $r2`
