### ISSUE TITLE
Enhance support for array taint obj in taint config

### ISSUE THREAD

**Issue by 75ACOL** [pascal-lab/Tai-e#73]
### Description
```java
import java.io.IOException;

public class TestTaiE2 {
    public static void main(String[] args) throws IOException {
        TestTaiE2 testTaiE2 = new TestTaiE2(args[0]);
        testTaiE2.sink();
    }
    private final String source;
    public TestTaiE2(String source) {
        this.source = source;
    }
    public void sink() throws IOException {
        Runtime.getRuntime().exec(source);
    }
}
```
**Expected vs. Actual Behavior**: The data flow from args to Runtime.getRuntime().exec(source) is to be found.
**Steps to Reproduce**: My taint-config.yml Configuration
```yaml
sources:
  - { kind: param, method: "<org.example.test.TestTaiE2: void main(java.lang.String[])>", index: 0 }
sinks:
  - { kind: call,  method: "<java.lang.Runtime: java.lang.Process exec(java.lang.String)>", index: 0 }
```
**Your Attempts to Resolve the Issue**: I'm not sure if it's supported, or if it's going to be used [Taint Analysis](https://tai-e.pascal-lab.net/docs/current/reference/en/taint-analysis.html)
**Runtime Environment**:  java19
**Tai-e Version**: 0.2.2
